from PyQt5.QtCore    import Qt
from PyQt5.QtCore    import QSize
from PyQt5.QtCore    import QRect
from PyQt5.QtCore    import QPoint
from PyQt5.QtCore    import pyqtSignal
from PyQt5.QtCore    import QFileInfo
from PyQt5.QtGui     import QStandardItemModel
from PyQt5.QtGui     import QStandardItem
from PyQt5.QtGui     import QPixmap
from PyQt5.QtGui     import QPainter
from PyQt5.QtGui     import QPen
from PyQt5.QtGui     import QBrush
from PyQt5.QtGui     import QColor
from PyQt5.QtGui     import QImage
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QSizePolicy
from PyQt5.QtWidgets import QWidget
from PyQt5.QtWidgets import QTabWidget
from PyQt5.QtWidgets import QTreeView
from PyQt5.QtWidgets import QGroupBox
from PyQt5.QtWidgets import QHBoxLayout
from PyQt5.QtWidgets import QVBoxLayout
from PyQt5.QtWidgets import QGridLayout
from PyQt5.QtWidgets import QComboBox
from PyQt5.QtWidgets import QPushButton
from PyQt5.QtWidgets import QRadioButton
from PyQt5.QtWidgets import QLabel
from PyQt5.QtWidgets import QProgressBar
from PyQt5.QtWidgets import QSlider
from PyQt5.QtWidgets import QCheckBox
from PyQt5.QtWidgets import QLineEdit
from PyQt5.QtWidgets import QButtonGroup
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtWidgets import QGroupBox

import PyQt5
